# Generated by Django 6.0 on 2026-01-06 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
                ('toxicity_score', models.FloatField()),
                ('detected_words', models.JSONField(default=list)),
                ('violation_type', models.CharField(choices=[('warning', 'Warning'), ('timeout', 'Timeout'), ('stream_stop', 'Stream Stopped')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_violations', to='chat.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'stream', '-created_at'], name='moderation__user_id_e7b8ca_idx'), models.Index(fields=['stream', '-created_at'], name='moderation__stream__e36264_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreamTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.IntegerField(default=60)),
                ('reason', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeouts', to='chat.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_timeouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'stream', 'is_active'], name='moderation__user_id_0ed7eb_idx')],
            },
        ),
    ]
