# Generated by Django 4.2.27 on 2026-01-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_onboarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_onboarded',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
